### PR TITLE
Fix favorites list not updating after deletion

### LINKED ISSUE #133: [PE-D][Tester C] Change in person's index not applied in favorite list
In the screenshot above, the index of a person named 'Temp Name' has been changed from 7 to 6, but the same person in favorite list still has index 7. This may confuse the user when the user needs to use the person's index. (e.g. when using `delete` or `edit`)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jinnieshin/ped#7

### PR DESCRIPTION
**Pull request by jugheadjones10**
closes #133

### CODE REVIEW

File: src/main/java/seedu/address/ui/FavoritesListPanel.java [hunk 1]
```diff
@@ -26,6 +27,8 @@ public class FavoritesListPanel extends UiPart<Region> {
     public FavoritesListPanel(ObservableList<Person> favoritesList, ObservableList<Person> filteredPersonList) {
         super(FXML);
         this.filteredPersonList = filteredPersonList;
+        filteredPersonList.addListener((ListChangeListener<Person>) change -> favoritesListView.refresh());
```
Comment (rexcyrio) [inline src/main/java/seedu/address/ui/FavoritesListPanel.java:30]: Does the favorites list refresh when the full list of contacts is edited (e.g., delete the first person in the full list)? Cause I see the parameter name as `filteredPersonList` which makes me a little confused.

File: src/main/java/seedu/address/ui/FavoritesListPanel.java [hunk 2]
```diff
@@ -43,7 +46,6 @@ protected void updateItem(Person person, boolean empty) {
                 setText(null);
             } else {
                 int filteredListPersonIndex = filteredPersonList.indexOf(person);
-                System.out.println("Filtered person index: " + filteredListPersonIndex);
```
Comment (rexcyrio) [inline src/main/java/seedu/address/ui/FavoritesListPanel.java:46]: Instead of deleting this line, you can consider using the `logger` to log this information.
