### PR TITLE
Fix edit command allowing duplicate email or phones

### LINKED ISSUE #131: [PE-D][Tester A] Edit that Result in Duplicate Person may Potentially Cause the App to Crash
I tried to edit a person, person 2 in this case, such that it would result in a duplicate person, with person 1, in this case.

The result Display Section would freeze, and the console gave an exception that is not handled properly. 

Subsequent Commands can be executed but the result Box still freezes. 

I suppose there would be an unhandled Duplicate Entries Exception for the Edit Command.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Yufannnn/ped#10

### LINKED ISSUE #134: [PE-D][Tester D] Possible to edit a person to have the same data fields as another person
It is possible to edit a person to have the exact same fields as another person, bypassing the condition that fields like emails do not be identical. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zrei/ped#6

### PR DESCRIPTION
**Pull request by niekis**
closes #131 
closes #134

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -60,7 +60,8 @@ public class EditCommand extends Command {
 
     public static final String MESSAGE_EDIT_PERSON_SUCCESS = "Edited Person: %1$s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book.";
+    public static final String MESSAGE_DUPLICATE_PERSON = "%1$s already exists in the address book. "
+            + "Duplicate Emails or Phone numbers are not allowed ";
```
Comment (rexcyrio) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:64]: Not sure if you meant to capitalise "Email" and "Phone"?

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -110,8 +111,10 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
-            throw new CommandException(MESSAGE_DUPLICATE_PERSON);
+        if (!model.canEdit(personToEdit, editedPerson)) {
+            String duplicateString = model.getDuplicateStringForEdit(editedPerson, personToEdit);
+            assert !duplicateString.isBlank() : "reported cannot edit, but no duplicate string found";
```
Comment (rexcyrio) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:116]: Maybe a better assert message could be:

"Unable to edit the person but no duplicate strings found"

File: src/main/java/seedu/address/model/person/UniquePersonList.java [hunk 3]
```diff
@@ -92,6 +93,29 @@ public String findDuplicatedString(Person duplicatedPerson) {
...
+     * {@code duplicateEditedPerson} and the entire address book, not considering any duplicates found between the
+     * {@code duplicateEditedPerson} and the {@code notCounted} entry.
+     * Returns empty {@code String} if no duplicates are found.
+     */
+    public String getDuplicateStringExceptFor(Person duplicatePerson, Person exceptFor) {
+        requireAllNonNull(duplicatePerson, exceptFor);
+
+        List<Person> tempList = new ArrayList<>(List.copyOf(internalList));
+        if (!tempList.remove(exceptFor)) {
+            throw new NoSuchElementException();
```
Comment (rexcyrio) [inline src/main/java/seedu/address/model/person/UniquePersonList.java:107]: Since we're dealing with `Person` objects, maybe a better exception to throw would be `PersonNotFoundException`?

**Review by rexcyrio — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 1 above)
Comment (minosx31) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:64]: There seems to be an extra space after `allowed`

Comment (niekis) [reply src/main/java/seedu/address/logic/commands/EditCommand.java:64]: oh should i not capitalize?
